# Boston AirBnb Data

In [1]:
# Python Imports

import pandas as pd
import numpy as np
from collections import Counter

### Cleaning of Listing Data

In [2]:
# Cleaning the listings data

# Loading data from csv files
listings_dataframe = pd.read_csv('listings.csv')

# replacing NaN values with 0
listings_dataframe.fillna(0, inplace=True)

# Extracting prices from the table
price = listings_dataframe['price']
prices=[]

# converting prices into a float value
for p in price:
    p=float(p[1:].replace(',',''))
    prices.append(p)

# replace the price column with the new column
listings_dataframe['price']=prices

# exclude the listings with 0 for price,beds,bedrooms,accomodates etc
listings_dataframe = listings_dataframe[listings_dataframe.bathrooms >0]
listings_dataframe = listings_dataframe[listings_dataframe.bedrooms > 0]
listings_dataframe = listings_dataframe[listings_dataframe.beds > 0]
listings_dataframe = listings_dataframe[listings_dataframe.price  > 0]
listings_dataframe = listings_dataframe[listings_dataframe.review_scores_rating  > 0]
listings_dataframe = listings_dataframe[listings_dataframe.reviews_per_month > 0]
listings_dataframe = listings_dataframe[listings_dataframe.accommodates  > 0]
listings_dataframe.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
1,3075044,https://www.airbnb.com/rooms/3075044,20160906204935,2016-09-07,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Small but cozy and quite room with a full size...,Charming and quiet room in a second floor 1910...,none,"The room is in Roslindale, a diverse and prima...",...,9.0,f,0.0,0.0,t,moderate,f,f,1,1.30
2,6976,https://www.airbnb.com/rooms/6976,20160906204935,2016-09-07,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...",none,The LOCATION: Roslindale is a safe and diverse...,...,10.0,f,0.0,0.0,f,moderate,t,f,1,0.47
3,1436513,https://www.airbnb.com/rooms/1436513,20160906204935,2016-09-07,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Most places you find in Boston are small howev...,Come experience the comforts of home away from...,none,Roslindale is a lovely little neighborhood loc...,...,10.0,f,0.0,0.0,f,moderate,f,f,1,1.00
4,7651065,https://www.airbnb.com/rooms/7651065,20160906204935,2016-09-07,Come Home to Boston,"My comfy, clean and relaxing home is one block...","Clean, attractive, private room, one block fro...","My comfy, clean and relaxing home is one block...",none,"I love the proximity to downtown, the neighbor...",...,10.0,f,0.0,0.0,f,flexible,f,f,1,2.25
5,12386020,https://www.airbnb.com/rooms/12386020,20160906204935,2016-09-07,Private Bedroom + Great Coffee,Super comfy bedroom plus your own bathroom in ...,Our sunny condo is located on the second and t...,Super comfy bedroom plus your own bathroom in ...,none,We love our corner of Roslindale! For quiet wa...,...,10.0,f,0.0,0.0,f,flexible,f,f,1,1.70

In [3]:
listings_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2506 entries, 1 to 3583
Data columns (total 95 columns):
id                                  2506 non-null int64
listing_url                         2506 non-null object
scrape_id                           2506 non-null int64
last_scraped                        2506 non-null object
name                                2506 non-null object
summary                             2506 non-null object
space                               2506 non-null object
description                         2506 non-null object
experiences_offered                 2506 non-null object
neighborhood_overview               2506 non-null object
notes                               2506 non-null object
transit                             2506 non-null object
access                              2506 non-null object
interaction                         2506 non-null object
house_rules                         2506 non-null object
thumbnail_url                       2506 non-null object
medium_url                          2506 non-null object
picture_url                         2506 non-null object
xl_picture_url                      2506 non-null object
host_id                             2506 non-null int64
host_url                            2506 non-null object
host_name                           2506 non-null object
host_since                          2506 non-null object
host_location                       2506 non-null object
host_about                          2506 non-null object
host_response_time                  2506 non-null object
host_response_rate                  2506 non-null object
host_acceptance_rate                2506 non-null object
host_is_superhost                   2506 non-null object
host_thumbnail_url                  2506 non-null object
host_picture_url                    2506 non-null object
host_neighbourhood                  2506 non-null object
host_listings_count                 2506 non-null int64
host_total_listings_count           2506 non-null int64
host_verifications                  2506 non-null object
host_has_profile_pic                2506 non-null object
host_identity_verified              2506 non-null object
street                              2506 non-null object
neighbourhood                       2506 non-null object
neighbourhood_cleansed              2506 non-null object
neighbourhood_group_cleansed        2506 non-null float64
city                                2506 non-null object
state                               2506 non-null object
zipcode                             2506 non-null object
market                              2506 non-null object
smart_location                      2506 non-null object
country_code                        2506 non-null object
country                             2506 non-null object
latitude                            2506 non-null float64
longitude                           2506 non-null float64
is_location_exact                   2506 non-null object
property_type                       2506 non-null object
room_type                           2506 non-null object
accommodates                        2506 non-null int64
bathrooms                           2506 non-null float64
bedrooms                            2506 non-null float64
beds                                2506 non-null float64
bed_type                            2506 non-null object
amenities                           2506 non-null object
square_feet                         2506 non-null float64
price                               2506 non-null float64
weekly_price                        2506 non-null object
monthly_price                       2506 non-null object
security_deposit                    2506 non-null object
cleaning_fee                        2506 non-null object
guests_included                     2506 non-null int64
extra_people                        2506 non-null object
minimum_nights                      2506 non-null int64
maximum_nights                      2506 non-null int64
calendar_updated                    2506 non-null object
has_availability                    2506 non-null float64
availability_30                     2506 non-null int64
availability_60                     2506 non-null int64
availability_90                     2506 non-null int64
availability_365                    2506 non-null int64
calendar_last_scraped               2506 non-null object
number_of_reviews                   2506 non-null int64
first_review                        2506 non-null object
last_review                         2506 non-null object
review_scores_rating                2506 non-null float64
review_scores_accuracy              2506 non-null float64
review_scores_cleanliness           2506 non-null float64
review_scores_checkin               2506 non-null float64
review_scores_communication         2506 non-null float64
review_scores_location              2506 non-null float64
review_scores_value                 2506 non-null float64
requires_license                    2506 non-null object
license                             2506 non-null float64
jurisdiction_names                  2506 non-null float64
instant_bookable                    2506 non-null object
cancellation_policy                 2506 non-null object
require_guest_profile_picture       2506 non-null object
require_guest_phone_verification    2506 non-null object
calculated_host_listings_count      2506 non-null int64
reviews_per_month                   2506 non-null float64
dtypes: float64(19), int64(15), object(61)
memory usage: 1.8+ MB

In [4]:
## We decide on the columns to take
final_dataframe = listings_dataframe[['host_response_rate','host_acceptance_rate','host_is_superhost','host_total_listings_count','host_identity_verified','latitude','longitude','accommodates','bathrooms','bedrooms','beds','bed_type','guests_included','minimum_nights','availability_365','number_of_reviews','review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value','instant_bookable','reviews_per_month']]
final_dataframe.head()

,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_identity_verified,latitude,longitude,accommodates,bathrooms,bedrooms,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month
1,100%,100%,f,1,t,42.286241,-71.134374,2,1.0,1.0,...,36,94.0,10.0,9.0,10.0,10.0,9.0,9.0,t,1.30
2,100%,88%,t,1,t,42.292438,-71.135765,2,1.0,1.0,...,41,98.0,10.0,9.0,10.0,10.0,9.0,10.0,f,0.47
3,100%,50%,f,1,f,42.281106,-71.121021,4,1.0,1.0,...,1,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,1.00
4,100%,100%,t,1,t,42.284512,-71.136258,2,1.5,1.0,...,29,99.0,10.0,10.0,10.0,10.0,9.0,10.0,f,2.25
5,100%,95%,t,2,t,42.291690,-71.131893,2,1.0,1.0,...,8,100.0,10.0,10.0,10.0,10.0,9.0,10.0,f,1.70

In [5]:
## We are going to categorically classify these columns into numerical value
for categorical_feature in ['neighbourhood_cleansed', 'property_type', 'room_type', 'bed_type','host_response_time','cancellation_policy']:
    final_dataframe = pd.concat([final_dataframe, pd.get_dummies(listings_dataframe[categorical_feature])], axis=1)
final_dataframe.fillna(0)
final_dataframe.head()

,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_identity_verified,latitude,longitude,accommodates,bathrooms,bedrooms,...,Real Bed,0,a few days or more,within a day,within a few hours,within an hour,flexible,moderate,strict,super_strict_30
1,100%,100%,f,1,t,42.286241,-71.134374,2,1.0,1.0,...,1,0,0,0,0,1,0,1,0,0
2,100%,88%,t,1,t,42.292438,-71.135765,2,1.0,1.0,...,1,0,0,0,1,0,0,1,0,0
3,100%,50%,f,1,f,42.281106,-71.121021,4,1.0,1.0,...,1,0,0,0,1,0,0,1,0,0
4,100%,100%,t,1,t,42.284512,-71.136258,2,1.5,1.0,...,1,0,0,0,0,1,1,0,0,0
5,100%,95%,t,2,t,42.291690,-71.131893,2,1.0,1.0,...,1,0,0,0,1,0,1,0,0,0

### Cleaning of Calendar Data

In [6]:
## We load the calendar file for the prices which we will use as target
target = pd.read_csv("calendar.csv")[['listing_id','price']]

###### SInce Calendar file is a timeseries of prices for each day, we get the mean of each price

In [7]:
## We get the unique listing values
target.listing_id.unique

## Here we clean the prices to get the numeric value 
target["price"] = target["price"].str.replace("[$,]", "").astype("float")
target.fillna(0) ### We remove all null values by replacing it with zero, since they are not available 

### Calendar data being a timeseries we get the mean price of all prices for each listing
target=target.groupby(['listing_id']).mean() 
target.head(20)

                 price
listing_id
3353         35.204819
5506        147.267442
6695        197.407407
6976         65.000000
8792        154.000000
9273        225.000000
9765        236.856354
9824        222.321981
9855        266.554945
9857        363.394813
9858        486.774725
9860        269.759207
9870        288.776243
9903        256.554945
10730       150.000000
10758       116.395349
10807        80.802469
10809       110.116279
10810       251.744186
10811       165.520548

# Linear Regression

In [ ]:
from sklearn import linear_model

In [ ]:
# Defining Independent variables and Dependent Variables
X = final_dataframe

Y = target["price"]

In [ ]:
# Splitting the data into training and testing dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=9)

In [ ]:
# Fitting the model using training data set
linear_regression_model = LinearRegression()
linear_regression_model.fit(X_train, Y_train)

In [ ]:
# Predicting prices for test data set
predictions = linear_regression_model.predict(X_test)

In [ ]:
# Checking the accuracy of the prediction using RootMeanSquare and R2 method
test_set_rmse = (np.sqrt(mean_squared_error(Y_test, predictions)))

test_set_r2 = r2_score(Y_test, predictions)

In [ ]:
# Printing out the accuracy metrics
print("Accuracy Metric using Root Mean Square Method", + test_set_rmse)
print("Accuracy Metric using R2 Method", + test_set_r2)

For Root mean square method the lower the value is, the better is the fit
And for R2 method, the closer the value is towards 1, the better the fit is